version: '3'
services:
  db:
    container_name: postgresql-crisperdx
    image: "postgres:12.4"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: crisperdx
      POSTGRES_USER: crisperdx
      POSTGRES_PASSWORD: crisperdx
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    container_name: redis-crisperdx
    image: "redis:6.0"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
